import type { DiceDelta } from '../core/types';

export type ModifierEffectId =
  | 'heal'
  | 'enemy_hp_mult'
  | 'enemy_projectile_speed_mult'
  | 'enemy_damage_mult'
  | 'player_damage_mult'
  | 'player_move_speed_mult'
  | 'player_attack_speed_mult'
  | 'gravity_mult'
  | 'damage_taken_mult'
  | 'aggro_delay_mult'
  | 'enemy_spawn_rate_mult'
  | 'hazard_frequency_mult'
  | 'player_heal_on_floor'
  | 'elite_spawn_chance'
  | 'cooldown_recovery_mult'
  | 'meter_gain_mult'
  | 'gold_find_mult'
  | 'dash_recovery_mult'
  | 'knockback_resist_mult'
  | 'floor_timer_mult';

export interface ModifierDef {
  id: string;
  name: string;
  description: string;
  delta: DiceDelta;
  exclusiveTag?: string;
  effectId: ModifierEffectId;
  params: Record<string, number>;
}

export const MODIFIER_DATABASE: readonly ModifierDef[] = [
  {
    id: 'hearth_of_kallos',
    name: 'Hearth of Kallos',
    description: 'Restore a modest breath of sanctified health before the next ascent.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 18 },
  },
  {
    id: 'frostdew_vial',
    name: 'Frostdew Vial',
    description: 'A chilled draught seals cuts with pale winter light.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 14 },
  },
  {
    id: 'void_suture',
    name: 'Void Suture',
    description: 'A black thread closes wounds without asking what it binds.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 20 },
  },
  {
    id: 'forge_balm',
    name: 'Forge Balm',
    description: 'Warm iron-salve knits flesh and steadies the weapon hand.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 16 },
  },
  {
    id: 'oracle_milk',
    name: 'Oracle Milk',
    description: 'A fate-soft tonic restores health with the taste of remembered rain.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 22 },
  },
  {
    id: 'saint_ember',
    name: 'Saint Ember',
    description: 'A coin-sized ember burns away pain without widening the dice.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 12 },
  },
  {
    id: 'moonwell_sip',
    name: 'Moonwell Sip',
    description: 'Silver water mends the body and leaves the range untouched.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 24 },
  },
  {
    id: 'kallos_mercy',
    name: 'Kallos Mercy',
    description: 'A quiet blessing restores health under the Council gaze.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 19 },
  },
  {
    id: 'ashen_lotus',
    name: 'Ashen Lotus',
    description: 'Petals of gray fire bloom over bruises and broken mail.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 15 },
  },
  {
    id: 'pilgrim_golden_oil',
    name: 'Pilgrim Golden Oil',
    description: 'Consecrated oil restores a clean measure of health.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 21 },
  },
  {
    id: 'veilwater_charm',
    name: 'Veilwater Charm',
    description: 'The charm cracks, spilling curative dusk across your wounds.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 17 },
  },
  {
    id: 'choir_salve',
    name: 'Choir Salve',
    description: 'A humming salve restores health with no bargain attached.',
    delta: 0,
    effectId: 'heal',
    params: { amount: 23 },
  },
  {
    id: 'frost_king_leniency',
    name: 'Frost-King Leniency',
    description: 'Enemy bodies frost over, slightly reducing their maximum health.',
    delta: -1,
    effectId: 'enemy_hp_mult',
    params: { mult: 0.92 },
  },
  {
    id: 'veiled_arrows',
    name: 'Veiled Arrows',
    description: 'Hostile projectiles drag through a soft void veil.',
    delta: -1,
    exclusiveTag: 'projectile_speed',
    effectId: 'enemy_projectile_speed_mult',
    params: { mult: 0.9 },
  },
  {
    id: 'kallos_sandals',
    name: 'Kallos Sandals',
    description: 'Your steps quicken with ceremonial gold-thread grace.',
    delta: -1,
    exclusiveTag: 'move_speed',
    effectId: 'player_move_speed_mult',
    params: { mult: 1.06 },
  },
  {
    id: 'tithe_of_patience',
    name: 'Tithe of Patience',
    description: 'Enemies hesitate a moment longer before committing to pursuit.',
    delta: -1,
    exclusiveTag: 'aggro_delay',
    effectId: 'aggro_delay_mult',
    params: { mult: 1.15 },
  },
  {
    id: 'bronze_aegis_thread',
    name: 'Bronze Aegis Thread',
    description: 'A bronze-lit ward modestly reduces incoming damage.',
    delta: -1,
    exclusiveTag: 'blood_tax',
    effectId: 'damage_taken_mult',
    params: { mult: 0.94 },
  },
  {
    id: 'spring_of_minor_stars',
    name: 'Spring of Minor Stars',
    description: 'Clearing a floor restores a small star-fed measure of health.',
    delta: -1,
    exclusiveTag: 'floor_heal',
    effectId: 'player_heal_on_floor',
    params: { amount: 5 },
  },
  {
    id: 'clockmaker_prayer',
    name: 'Clockmaker Prayer',
    description: 'Ability cooldowns recover a little faster under fate-wound gears.',
    delta: -1,
    exclusiveTag: 'cooldown_recovery',
    effectId: 'cooldown_recovery_mult',
    params: { mult: 1.08 },
  },
  {
    id: 'silver_dice_inlay',
    name: 'Silver Dice Inlay',
    description: 'Dice meter offerings arrive with slightly greater momentum.',
    delta: -1,
    effectId: 'meter_gain_mult',
    params: { mult: 1.1 },
  },
  {
    id: 'seraphic_wrist',
    name: 'Seraphic Wrist',
    description: 'Your attack cadence sharpens with restrained divine timing.',
    delta: -1,
    exclusiveTag: 'attack_speed',
    effectId: 'player_attack_speed_mult',
    params: { mult: 1.05 },
  },
  {
    id: 'low_gravity_psalm',
    name: 'Low-Gravity Psalm',
    description: 'A psalm loosens the arena gravity just enough for softer arcs.',
    delta: -1,
    exclusiveTag: 'gravity_flux',
    effectId: 'gravity_mult',
    params: { mult: 0.95 },
  },
  {
    id: 'hare_moon_discipline',
    name: 'Hare-Moon Discipline',
    description: 'Dodges settle faster, inviting cleaner repositioning.',
    delta: -1,
    exclusiveTag: 'dash_recovery',
    effectId: 'dash_recovery_mult',
    params: { mult: 1.1 },
  },
  {
    id: 'anvil_spine',
    name: 'Anvil Spine',
    description: 'Your stance resists knockback with forge-tempered resolve.',
    delta: -1,
    exclusiveTag: 'knockback_resist',
    effectId: 'knockback_resist_mult',
    params: { mult: 1.12 },
  },
  {
    id: 'winter_court_decree',
    name: 'Winter Court Decree',
    description: 'A deep frost mandate greatly lowers enemy maximum health.',
    delta: -2,
    effectId: 'enemy_hp_mult',
    params: { mult: 0.82 },
  },
  {
    id: 'void_muffle',
    name: 'Void Muffle',
    description: 'Enemy projectiles crawl through soundless black velvet.',
    delta: -2,
    exclusiveTag: 'projectile_speed',
    effectId: 'enemy_projectile_speed_mult',
    params: { mult: 0.78 },
  },
  {
    id: 'kallos_gilded_aegis',
    name: 'Kallos Gilded Aegis',
    description: 'A royal ward substantially softens incoming damage.',
    delta: -2,
    exclusiveTag: 'blood_tax',
    effectId: 'damage_taken_mult',
    params: { mult: 0.86 },
  },
  {
    id: 'star_runner_oath',
    name: 'Star-Runner Oath',
    description: 'Your movement surges with the impossible gait of constellations.',
    delta: -2,
    exclusiveTag: 'move_speed',
    effectId: 'player_move_speed_mult',
    params: { mult: 1.12 },
  },
  {
    id: 'hourglass_absolution',
    name: 'Hourglass Absolution',
    description: 'Cooldowns recover much faster while fate sand runs backward.',
    delta: -2,
    exclusiveTag: 'cooldown_recovery',
    effectId: 'cooldown_recovery_mult',
    params: { mult: 1.18 },
  },
  {
    id: 'twinned_meter_star',
    name: 'Twinned Meter Star',
    description: 'Dice meter gains are blessed with a second unseen pulse.',
    delta: -2,
    effectId: 'meter_gain_mult',
    params: { mult: 1.22 },
  },
  {
    id: 'forge_lion_favor',
    name: 'Forge-Lion Favor',
    description: 'Your strikes carry a stronger ember-backed bite.',
    delta: -2,
    exclusiveTag: 'player_damage',
    effectId: 'player_damage_mult',
    params: { mult: 1.12 },
  },
  {
    id: 'mending_constellation',
    name: 'Mending Constellation',
    description: 'Each cleared floor returns a generous star-patterned heal.',
    delta: -2,
    exclusiveTag: 'floor_heal',
    effectId: 'player_heal_on_floor',
    params: { amount: 12 },
  },
  {
    id: 'sleeping_hounds_edict',
    name: 'Sleeping Hounds Edict',
    description: 'Enemy aggression wakes much later under a divine hush.',
    delta: -2,
    exclusiveTag: 'aggro_delay',
    effectId: 'aggro_delay_mult',
    params: { mult: 1.35 },
  },
  {
    id: 'featherfall_covenant',
    name: 'Featherfall Covenant',
    description: 'Arena gravity becomes dramatically gentler and easier to read.',
    delta: -2,
    exclusiveTag: 'gravity_flux',
    effectId: 'gravity_mult',
    params: { mult: 0.88 },
  },
  {
    id: 'rabbit_saint_heel',
    name: 'Rabbit-Saint Heel',
    description: 'Dodges recover with uncanny sacred elasticity.',
    delta: -2,
    exclusiveTag: 'dash_recovery',
    effectId: 'dash_recovery_mult',
    params: { mult: 1.22 },
  },
  {
    id: 'quiet_muster',
    name: 'Quiet Muster',
    description: 'Enemy reinforcements arrive in thinner, less frantic waves.',
    delta: -2,
    exclusiveTag: 'enemy_spawn_rate',
    effectId: 'enemy_spawn_rate_mult',
    params: { mult: 0.86 },
  },
  {
    id: 'iron_rooted_foes',
    name: 'Iron-Rooted Foes',
    description: 'Enemies anchor themselves with extra health.',
    delta: 1,
    effectId: 'enemy_hp_mult',
    params: { mult: 1.12 },
  },
  {
    id: 'needle_rain',
    name: 'Needle Rain',
    description: 'Hostile shots fly faster, bright and hard to ignore.',
    delta: 1,
    exclusiveTag: 'projectile_speed',
    effectId: 'enemy_projectile_speed_mult',
    params: { mult: 1.12 },
  },
  {
    id: 'emberclaw_edict',
    name: 'Emberclaw Edict',
    description: 'Enemy attacks bite harder with forge-fed sparks.',
    delta: 1,
    exclusiveTag: 'enemy_damage',
    effectId: 'enemy_damage_mult',
    params: { mult: 1.1 },
  },
  {
    id: 'blood_tax_minor',
    name: 'Minor Blood Tax',
    description: 'The Council collects a small surcharge from each wound.',
    delta: 1,
    exclusiveTag: 'blood_tax',
    effectId: 'damage_taken_mult',
    params: { mult: 1.08 },
  },
  {
    id: 'heavy_star_weather',
    name: 'Heavy Star Weather',
    description: 'Gravity presses down harder across the arena.',
    delta: 1,
    exclusiveTag: 'gravity_flux',
    effectId: 'gravity_mult',
    params: { mult: 1.1 },
  },
  {
    id: 'tarred_greaves',
    name: 'Tarred Greaves',
    description: 'Your movement slows as black fate-tar grips each step.',
    delta: 1,
    exclusiveTag: 'move_speed',
    effectId: 'player_move_speed_mult',
    params: { mult: 0.94 },
  },
  {
    id: 'wakeful_hounds',
    name: 'Wakeful Hounds',
    description: 'Enemies notice you sooner and close the arena faster.',
    delta: 1,
    exclusiveTag: 'aggro_delay',
    effectId: 'aggro_delay_mult',
    params: { mult: 0.85 },
  },
  {
    id: 'thorn_candles',
    name: 'Thorn Candles',
    description: 'Hazards flare more often in painful ceremonial rhythm.',
    delta: 1,
    exclusiveTag: 'hazard_frequency',
    effectId: 'hazard_frequency_mult',
    params: { mult: 1.15 },
  },
  {
    id: 'louder_muster',
    name: 'Louder Muster',
    description: 'Enemy waves gather with slightly greater urgency.',
    delta: 1,
    exclusiveTag: 'enemy_spawn_rate',
    effectId: 'enemy_spawn_rate_mult',
    params: { mult: 1.1 },
  },
  {
    id: 'crowned_elite_whisper',
    name: 'Crowned Elite Whisper',
    description: 'Elite presence becomes a little more likely in future fights.',
    delta: 1,
    exclusiveTag: 'elite_spawn_chance',
    effectId: 'elite_spawn_chance',
    params: { chance: 0.08 },
  },
  {
    id: 'rusted_clockhands',
    name: 'Rusted Clockhands',
    description: 'Cooldown recovery drags under corroded fate machinery.',
    delta: 1,
    exclusiveTag: 'cooldown_recovery',
    effectId: 'cooldown_recovery_mult',
    params: { mult: 0.92 },
  },
  {
    id: 'shortened_candle',
    name: 'Shortened Candle',
    description: 'Fast-clear windows tighten as the Council trims the wick.',
    delta: 1,
    exclusiveTag: 'floor_timer',
    effectId: 'floor_timer_mult',
    params: { mult: 0.92 },
  },
  {
    id: 'titan_blooded_foes',
    name: 'Titan-Blooded Foes',
    description: 'Enemies swell with a severe reserve of health.',
    delta: 2,
    effectId: 'enemy_hp_mult',
    params: { mult: 1.25 },
  },
  {
    id: 'comet_needle_storm',
    name: 'Comet Needle Storm',
    description: 'Hostile projectiles tear forward with alarming speed.',
    delta: 2,
    exclusiveTag: 'projectile_speed',
    effectId: 'enemy_projectile_speed_mult',
    params: { mult: 1.26 },
  },
  {
    id: 'red_forge_sentence',
    name: 'Red Forge Sentence',
    description: 'Enemy damage rises sharply beneath a blazing verdict.',
    delta: 2,
    exclusiveTag: 'enemy_damage',
    effectId: 'enemy_damage_mult',
    params: { mult: 1.22 },
  },
  {
    id: 'blood_tax_major',
    name: 'Major Blood Tax',
    description: 'Every mistake pays dearly into the Council chalice.',
    delta: 2,
    exclusiveTag: 'blood_tax',
    effectId: 'damage_taken_mult',
    params: { mult: 1.16 },
  },
  {
    id: 'collapsed_sky',
    name: 'Collapsed Sky',
    description: 'Gravity becomes a punishing celestial hand.',
    delta: 2,
    exclusiveTag: 'gravity_flux',
    effectId: 'gravity_mult',
    params: { mult: 1.22 },
  },
  {
    id: 'chainbound_steps',
    name: 'Chainbound Steps',
    description: 'Movement slows under spectral fetters and gold-cold law.',
    delta: 2,
    exclusiveTag: 'move_speed',
    effectId: 'player_move_speed_mult',
    params: { mult: 0.88 },
  },
  {
    id: 'instant_hunt_proclamation',
    name: 'Instant Hunt Proclamation',
    description: 'Enemies acquire targets almost immediately after spawning.',
    delta: 2,
    exclusiveTag: 'aggro_delay',
    effectId: 'aggro_delay_mult',
    params: { mult: 0.68 },
  },
  {
    id: 'black_thorn_procession',
    name: 'Black-Thorn Procession',
    description: 'Hazards recur in a dense and ritualized cadence.',
    delta: 2,
    exclusiveTag: 'hazard_frequency',
    effectId: 'hazard_frequency_mult',
    params: { mult: 1.35 },
  },
  {
    id: 'war_bell_muster',
    name: 'War-Bell Muster',
    description: 'Enemy waves answer the bell with far greater haste.',
    delta: 2,
    exclusiveTag: 'enemy_spawn_rate',
    effectId: 'enemy_spawn_rate_mult',
    params: { mult: 1.22 },
  },
  {
    id: 'many_crowned_night',
    name: 'Many-Crowned Night',
    description: 'Elite presence becomes notably more likely.',
    delta: 2,
    exclusiveTag: 'elite_spawn_chance',
    effectId: 'elite_spawn_chance',
    params: { chance: 0.18 },
  },
  {
    id: 'shattered_clocktower',
    name: 'Shattered Clocktower',
    description: 'Cooldown recovery slows beneath broken divine machinery.',
    delta: 2,
    exclusiveTag: 'cooldown_recovery',
    effectId: 'cooldown_recovery_mult',
    params: { mult: 0.82 },
  },
  {
    id: 'dying_sun_sprint',
    name: 'Dying Sun Sprint',
    description: 'Fast-clear timing becomes brutally narrow and bright.',
    delta: 2,
    exclusiveTag: 'floor_timer',
    effectId: 'floor_timer_mult',
    params: { mult: 0.82 },
  },
];

export const MODIFIER_BY_ID: ReadonlyMap<string, ModifierDef> = new Map(
  MODIFIER_DATABASE.map((modifier) => [modifier.id, modifier]),
);

export function getModifierById(id: string): ModifierDef | undefined {
  return MODIFIER_BY_ID.get(id);
}

export function getModifiersByDelta(delta: DiceDelta): ModifierDef[] {
  return MODIFIER_DATABASE.filter((modifier) => modifier.delta === delta);
}
