import type { OwnedRelic } from '../core/RunState';
import type { RelicBand, RelicRarity } from '../core/types';

export interface RelicDef {
  id: string;
  name: string;
  description: string;
  rarity: RelicRarity;
  band: RelicBand;
  effectId: string;
  params: Record<string, number>;
  weight: number;
}

export const ALL_RELICS: readonly RelicDef[] = [
  {
    id: 'marrow-lantern',
    name: 'Marrow Lantern',
    description: 'Kills rekindle a small amount of health, rewarding clean room routing over passive sustain.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'marrow_lantern',
    params: { healOnKill: 3 },
    weight: 16,
  },
  {
    id: 'bulwark-rosary',
    name: 'Bulwark Rosary',
    description: 'Incoming damage is reduced while you keep your relic slot committed to defense.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'bulwark_rosary',
    params: { incomingDamageMultBonus: -0.1 },
    weight: 15,
  },
  {
    id: 'duststep-greaves',
    name: 'Duststep Greaves',
    description: 'Move faster after choosing survival, making repositioning the defensive answer.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'duststep_greaves',
    params: { moveSpeedMultBonus: 0.08 },
    weight: 15,
  },
  {
    id: 'hush-mantle',
    name: 'Hush Mantle',
    description: 'Perfect defensive inputs gain a wider timing window for deliberate counterplay.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'hush_mantle',
    params: { perfectWindowBonus: 0.035 },
    weight: 14,
  },
  {
    id: 'lifeline-sigil',
    name: 'Lifeline Sigil',
    description: 'Dice meter builds faster, converting survival play into more frequent agency.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'lifeline_sigil',
    params: { meterChargeMultBonus: 0.12 },
    weight: 14,
  },
  {
    id: 'rainward-boots',
    name: 'Rainward Boots',
    description: 'A light movement relic that helps dodge patterns without changing your damage plan.',
    rarity: 'COMMON',
    band: 'SURVIVAL',
    effectId: 'rainward_boots',
    params: { moveSpeedMultBonus: 0.05, perfectWindowBonus: 0.015 },
    weight: 13,
  },
  {
    id: 'anchor-clasp',
    name: 'Anchor Clasp',
    description: 'Ascension charge channels faster, shortening the most dangerous carry moments.',
    rarity: 'RARE',
    band: 'SURVIVAL',
    effectId: 'anchor_clasp',
    params: { orbChargeRateMultBonus: 0.18, orbCarryMoveSpeedMultBonus: 0.04 },
    weight: 9,
  },
  {
    id: 'second-breath',
    name: 'Second Breath',
    description: 'Gain an extra dash charge so survival comes from spacing, not standing still.',
    rarity: 'RARE',
    band: 'SURVIVAL',
    effectId: 'second_breath',
    params: { dashChargesBonus: 1 },
    weight: 8,
  },
  {
    id: 'saffron-mercy',
    name: 'Saffron Mercy',
    description: 'Kills heal more and feed the dice meter, turning stabilizing clears into tempo.',
    rarity: 'RARE',
    band: 'SURVIVAL',
    effectId: 'saffron_mercy',
    params: { healOnKill: 5, meterChargeMultBonus: 0.08 },
    weight: 8,
  },
  {
    id: 'patient-halo',
    name: 'Patient Halo',
    description: 'Perfect timing is easier, but the relic offers no raw damage shortcut.',
    rarity: 'RARE',
    band: 'SURVIVAL',
    effectId: 'patient_halo',
    params: { perfectWindowBonus: 0.06 },
    weight: 8,
  },
  {
    id: 'quiet-parry',
    name: 'Quiet Parry',
    description: 'Tighter defense pays back with a small critical opening after precise play.',
    rarity: 'RARE',
    band: 'SURVIVAL',
    effectId: 'quiet_parry',
    params: { perfectWindowBonus: 0.04, critChanceBonus: 0.04 },
    weight: 7,
  },
  {
    id: 'gateward-aegis',
    name: 'Gateward Aegis',
    description: 'A heavy defensive relic that makes mistakes less lethal and parry timing kinder.',
    rarity: 'EPIC',
    band: 'SURVIVAL',
    effectId: 'gateward_aegis',
    params: { incomingDamageMultBonus: -0.16, perfectWindowBonus: 0.04 },
    weight: 4,
  },
  {
    id: 'bastion-tether',
    name: 'Bastion Tether',
    description: 'Orb delivery becomes safer through faster charge progress and reduced chip damage.',
    rarity: 'EPIC',
    band: 'SURVIVAL',
    effectId: 'bastion_tether',
    params: { orbChargeRateMultBonus: 0.25, incomingDamageMultBonus: -0.06 },
    weight: 4,
  },
  {
    id: 'last-ember',
    name: 'Last Ember',
    description: 'Enemy kills restore a large burst of health, encouraging clutch aggression when behind.',
    rarity: 'LEGENDARY',
    band: 'SURVIVAL',
    effectId: 'last_ember',
    params: { healOnKill: 12, meterChargeMultBonus: 0.1 },
    weight: 1,
  },
  {
    id: 'kinetic-vow',
    name: 'Kinetic Vow',
    description: 'Momentum becomes offense: move faster and deal more damage without changing your kit.',
    rarity: 'RARE',
    band: 'CORE',
    effectId: 'kinetic_vow',
    params: { moveSpeedMultBonus: 0.1, damageMultBonus: 0.06 },
    weight: 9,
  },
  {
    id: 'chronal-nick',
    name: 'Chronal Nick',
    description: 'A time-slip relic that widens precision windows and slightly extends boss damage phases.',
    rarity: 'EPIC',
    band: 'CORE',
    effectId: 'chronal_nick',
    params: { perfectWindowBonus: 0.08, dpsWindowBonusSeconds: 1.5 },
    weight: 4,
  },
  {
    id: 'starvein-core',
    name: 'Starvein Core',
    description: 'Once each DPS window starts, add 4 seconds to that window before the core burns out.',
    rarity: 'LEGENDARY',
    band: 'CORE',
    effectId: 'ascendant_core',
    params: { dpsWindowBonusSeconds: 4 },
    weight: 1,
  },
  {
    id: 'paired-omens',
    name: 'Paired Omens',
    description: 'A twin-fate relic: gain an extra dash charge and a sharper chance to crit.',
    rarity: 'EPIC',
    band: 'CORE',
    effectId: 'paired_omens',
    params: { dashChargesBonus: 1, critChanceBonus: 0.06, bonusOfferCount: 1 },
    weight: 4,
  },
  {
    id: 'heavy-auspice',
    name: 'Heavy Auspice',
    description: 'Loaded fate turns meter gain into pressure, with a modest damage lift attached.',
    rarity: 'RARE',
    band: 'CORE',
    effectId: 'heavy_auspice',
    params: { meterChargeMultBonus: 0.28, damageMultBonus: 0.05 },
    weight: 8,
  },
  {
    id: 'crooked-pips',
    name: 'Crooked Pips',
    description: 'A bent-die relic that nudges future reward rolls away from the worst outcomes.',
    rarity: 'RARE',
    band: 'CORE',
    effectId: 'bent_die',
    params: { victoryRollBonus: 1, lowRollFloor: 7 },
    weight: 7,
  },
  {
    id: 'mirror-step',
    name: 'Mirror Step',
    description: 'Add a dash charge, asking you to spend mobility actively instead of banking defense.',
    rarity: 'COMMON',
    band: 'CORE',
    effectId: 'mirror_step',
    params: { dashChargesBonus: 1 },
    weight: 13,
  },
  {
    id: 'runic-flywheel',
    name: 'Runic Flywheel',
    description: 'Dice meter fills faster from normal play, smoothing access to run-shaping decisions.',
    rarity: 'COMMON',
    band: 'CORE',
    effectId: 'runic_flywheel',
    params: { meterChargeMultBonus: 0.18 },
    weight: 14,
  },
  {
    id: 'graviton-spur',
    name: 'Graviton Spur',
    description: 'A hybrid movement relic that quickens both traversal and Ascension charge handling.',
    rarity: 'RARE',
    band: 'CORE',
    effectId: 'graviton_spur',
    params: { moveSpeedMultBonus: 0.08, orbChargeRateMultBonus: 0.12 },
    weight: 8,
  },
  {
    id: 'carved-countdown',
    name: 'Carved Countdown',
    description: 'Each DPS window opens a little longer, creating room for slower burst rotations.',
    rarity: 'COMMON',
    band: 'CORE',
    effectId: 'carved_countdown',
    params: { dpsWindowBonusSeconds: 1 },
    weight: 12,
  },
  {
    id: 'hand-of-quarters',
    name: 'Hand of Quarters',
    description: 'Critical chance and meter gain rise together for builds that cycle specials often.',
    rarity: 'RARE',
    band: 'CORE',
    effectId: 'hand_of_quarters',
    params: { critChanceBonus: 0.05, meterChargeMultBonus: 0.12 },
    weight: 8,
  },
  {
    id: 'sundered-metronome',
    name: 'Sundered Metronome',
    description: 'A rhythm relic that adds real damage while preserving a small precision safety net.',
    rarity: 'EPIC',
    band: 'CORE',
    effectId: 'sundered_metronome',
    params: { damageMultBonus: 0.12, perfectWindowBonus: 0.03 },
    weight: 4,
  },
  {
    id: 'compass-of-return',
    name: 'Compass of Return',
    description: 'A forgiving core relic: light healing on kills and a small movement lift.',
    rarity: 'COMMON',
    band: 'CORE',
    effectId: 'compass_of_return',
    params: { healOnKill: 2, moveSpeedMultBonus: 0.04 },
    weight: 13,
  },
  {
    id: 'glass-covenant',
    name: 'Glass Covenant',
    description: 'A glass-pact relic: deal much more damage, but every mistake hurts harder.',
    rarity: 'EPIC',
    band: 'GREED_DAMAGE',
    effectId: 'glass_pact',
    params: { damageMultBonus: 0.3, incomingDamageMultBonus: 0.2 },
    weight: 4,
  },
  {
    id: 'crown-of-ruin',
    name: 'Crown of Ruin',
    description: 'A legendary damage crown with major crit power and a dangerous incoming damage cost.',
    rarity: 'LEGENDARY',
    band: 'GREED_DAMAGE',
    effectId: 'crown_of_ruin',
    params: { damageMultBonus: 0.22, critChanceBonus: 0.1, incomingDamageMultBonus: 0.12 },
    weight: 1,
  },
  {
    id: 'redline-needle',
    name: 'Redline Needle',
    description: 'A simple damage relic for players who want faster clears over safer ones.',
    rarity: 'COMMON',
    band: 'GREED_DAMAGE',
    effectId: 'redline_needle',
    params: { damageMultBonus: 0.1 },
    weight: 14,
  },
  {
    id: 'vorpal-decimal',
    name: 'Vorpal Decimal',
    description: 'Critical chance rises sharply, favoring burst windows and high-hit-count weapons.',
    rarity: 'RARE',
    band: 'GREED_DAMAGE',
    effectId: 'vorpal_decimal',
    params: { critChanceBonus: 0.12 },
    weight: 8,
  },
  {
    id: 'ashmaker-mandate',
    name: 'Ashmaker Mandate',
    description: 'Raw damage increases enough to end threats before defensive value would matter.',
    rarity: 'EPIC',
    band: 'GREED_DAMAGE',
    effectId: 'ashmaker_mandate',
    params: { damageMultBonus: 0.16 },
    weight: 4,
  },
  {
    id: 'ravenous-coin',
    name: 'Ravenous Coin',
    description: 'Gain damage and meter pace, asking you to convert greed into constant pressure.',
    rarity: 'COMMON',
    band: 'GREED_DAMAGE',
    effectId: 'ravenous_coin',
    params: { damageMultBonus: 0.06, meterChargeMultBonus: 0.18 },
    weight: 13,
  },
  {
    id: 'bloodlit-lens',
    name: 'Bloodlit Lens',
    description: 'A crit-focused lens that also raises baseline damage for shorter boss phases.',
    rarity: 'RARE',
    band: 'GREED_DAMAGE',
    effectId: 'bloodlit_lens',
    params: { critChanceBonus: 0.08, damageMultBonus: 0.08 },
    weight: 8,
  },
  {
    id: 'overclock-brand',
    name: 'Overclock Brand',
    description: 'Move and hit faster, but the unstable brand makes enemy contact more punishing.',
    rarity: 'RARE',
    band: 'GREED_DAMAGE',
    effectId: 'overclock_brand',
    params: { moveSpeedMultBonus: 0.12, damageMultBonus: 0.08, incomingDamageMultBonus: 0.08 },
    weight: 7,
  },
  {
    id: 'hunted-halo',
    name: 'Hunted Halo',
    description: 'Boss mechanics progress faster and damage rises, but pressure against you rises too.',
    rarity: 'EPIC',
    band: 'GREED_DAMAGE',
    effectId: 'hunted_halo',
    params: { damageMultBonus: 0.14, orbChargeRateMultBonus: 0.2, incomingDamageMultBonus: 0.1 },
    weight: 4,
  },
  {
    id: 'final-spark',
    name: 'Final Spark',
    description: 'Damage windows last longer and hit harder, ideal for risky boss-burn strategies.',
    rarity: 'LEGENDARY',
    band: 'GREED_DAMAGE',
    effectId: 'final_spark',
    params: { dpsWindowBonusSeconds: 2, damageMultBonus: 0.18 },
    weight: 1,
  },
  {
    id: 'razor-dividend',
    name: 'Razor Dividend',
    description: 'A light greed relic that splits value between crit chance and consistent damage.',
    rarity: 'COMMON',
    band: 'GREED_DAMAGE',
    effectId: 'razor_dividend',
    params: { critChanceBonus: 0.05, damageMultBonus: 0.04 },
    weight: 13,
  },
  {
    id: 'iron-hunger',
    name: 'Iron Hunger',
    description: 'Damage rises, and kills return just enough health to keep aggressive routes alive.',
    rarity: 'RARE',
    band: 'GREED_DAMAGE',
    effectId: 'iron_hunger',
    params: { damageMultBonus: 0.1, healOnKill: 2 },
    weight: 8,
  },
  {
    id: 'golden-scar',
    name: 'Golden Scar',
    description: 'A dangerous damage spike that narrows perfect timing and increases incoming damage.',
    rarity: 'EPIC',
    band: 'GREED_DAMAGE',
    effectId: 'golden_scar',
    params: { damageMultBonus: 0.2, perfectWindowBonus: -0.02, incomingDamageMultBonus: 0.12 },
    weight: 4,
  },
] as const;

export function getRelicById(id: string): RelicDef | undefined {
  return ALL_RELICS.find((relic) => relic.id === id);
}

export function toOwnedRelic(relic: RelicDef): OwnedRelic {
  return {
    id: relic.id,
    name: relic.name,
    rarity: relic.rarity,
    band: relic.band,
    effectId: relic.effectId,
    params: { ...relic.params },
  };
}
